In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

from random import randint
import matplotlib.pyplot as plt

In [2]:
class NetGirl(nn.Module):
    def __init__(self, input_dim, num_hidden, output_dim):
        super().__init__()
        self.layer1 = nn.Linear(input_dim, num_hidden)
        self.layer2 = nn.Linear(num_hidden, output_dim)

    def forward(self, x):
        x = self.layer1(x)
        x = F.tanh(x)
        x = self.layer2(x)
        x = F.tanh(x)
        return x

In [3]:
model = NetGirl(3, 2, 1)
print(model)
print(list(model.parameters()))

# обучающая выборка (она же полная выборка)
x_train = torch.FloatTensor([(-1, -1, -1), (-1, -1, 1), (-1, 1, -1), (-1, 1, 1),
                            (1, -1, -1), (1, -1, 1), (1, 1, -1), (1, 1, 1)])
y_train = torch.FloatTensor([-1, 1, -1, 1, -1, 1, -1, -1]).unsqueeze(1)  # Reshape to [8, 1]
total = len(y_train)


print(x_train.shape)
print(y_train.shape)

NetGirl(
  (layer1): Linear(in_features=3, out_features=2, bias=True)
  (layer2): Linear(in_features=2, out_features=1, bias=True)
)
[Parameter containing:
tensor([[ 0.0380,  0.3174, -0.3790],
        [ 0.0707, -0.5738, -0.0890]], requires_grad=True), Parameter containing:
tensor([-0.3323,  0.3051], requires_grad=True), Parameter containing:
tensor([[-0.0006, -0.3774]], requires_grad=True), Parameter containing:
tensor([0.4177], requires_grad=True)]
torch.Size([8, 3])
torch.Size([8, 1])


In [4]:

optimizer = optim.RMSprop(params=model.parameters(), lr=0.01)
loss_func = torch.nn.MSELoss()

model.train()

for _ in range(1000):
    k = randint(0, total-1)
    y = model(x_train[k])
    loss = loss_func(y, y_train[k])

    print(f"Итерация {_+1}, номер {k+1}, ошибка: {loss.data.item():.4f}")
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

model.eval()

# тестирование обученной НС
for x, d in zip(x_train, y_train):
    with torch.no_grad():
        y = model(x)
        print(f"Выходное значение НС: {y.data.item():.4f} => {d.item():.4f}")

Итерация 1, номер 8, ошибка: 2.1912
Итерация 2, номер 4, ошибка: 0.4318
Итерация 3, номер 6, ошибка: 0.8628
Итерация 4, номер 7, ошибка: 1.8880
Итерация 5, номер 3, ошибка: 1.8243
Итерация 6, номер 5, ошибка: 1.3630
Итерация 7, номер 7, ошибка: 1.1512
Итерация 8, номер 5, ошибка: 0.8739
Итерация 9, номер 8, ошибка: 1.1223
Итерация 10, номер 3, ошибка: 0.9726
Итерация 11, номер 7, ошибка: 0.4456
Итерация 12, номер 5, ошибка: 0.4362
Итерация 13, номер 1, ошибка: 0.6229
Итерация 14, номер 7, ошибка: 0.2673
Итерация 15, номер 4, ошибка: 0.8255
Итерация 16, номер 7, ошибка: 0.2459
Итерация 17, номер 1, ошибка: 0.4152
Итерация 18, номер 2, ошибка: 0.7929
Итерация 19, номер 2, ошибка: 0.5477
Итерация 20, номер 3, ошибка: 0.4142
Итерация 21, номер 5, ошибка: 0.1624
Итерация 22, номер 7, ошибка: 0.1284
Итерация 23, номер 4, ошибка: 0.4020
Итерация 24, номер 1, ошибка: 0.3423
Итерация 25, номер 2, ошибка: 0.3608
Итерация 26, номер 4, ошибка: 0.2402
Итерация 27, номер 2, ошибка: 0.2410
Итерация 2