In [ ]:
import torch

In [6]:
t = torch.tensor([1, 2, 3, 4, 5])
print(t)

t1 = torch.empty([2, 3], dtype=torch.float32)
print(t1)

t2 = torch.zeros([2, 3], dtype=torch.float32)
print(t2)

t3 = torch.ones([2, 3], dtype=torch.float32)
print(t3)

t4 = torch.arange(0, 10, 2, dtype=torch.float32)
print(t4)

print(t4.shape)
print(t4.dtype)


tensor([1, 2, 3, 4, 5])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([0., 2., 4., 6., 8.])
torch.Size([5])
torch.float32


In [9]:
t5 = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
print(t5)
print(t5.shape)
print(t5.dtype)
print(t5[0, 1])  # Accessing element at row 0, column 1
print(t5.dim())  # Accessing the number of dimensions

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])
torch.float32
tensor(2.)
2
